### ISSUE TITLE
 KeyError: 'ffmpeg'

### ISSUE THREAD

**Issue by TimonSchatz** [alexmill/website_notebooks#1]
I am getting this Error at rendering do you know why?
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-63-c9b8b0dc7a58> in <module>()
    175                               interval=interval, blit=True, init_func=init)
    176 
--> 177 HTML(ani.to_html5_video())

~\Anaconda3\lib\site-packages\matplotlib\animation.py in to_html5_video(self, embed_limit)
   1407                 # We create a writer manually so that we can get the
   1408                 # appropriate size for the tag
-> 1409                 Writer = writers[rcParams['animation.writer']]
   1410                 writer = Writer(codec='h264',
   1411                                 bitrate=rcParams['animation.bitrate'],

~\Anaconda3\lib\site-packages\matplotlib\animation.py in __getitem__(self, name)
    168         if not self.avail:
    169             raise RuntimeError("No MovieWriters available!")
--> 170         return self.avail[name]
    171 
    172 writers = MovieWriterRegistry()

KeyError: 'ffmpeg'

**Comment by alexmill** [comment]
I just added the following lines to the notebook.

```python
# If you get the "KeyError: 'ffmpeg'" error (as you will if you run this on Binder),
# then your system does not have the ffmpeg video library installed.
```

As I mention there, you will simply need to comment out the line `HTML(ani.to_html5_video())` and replace it with:

```python
from IPython.display import Image as DisplayImage
ani.save('./animation.gif', writer='imagemagick')
DisplayImage(url='./animation.gif')
```
